# SwiftLint Configuration for Vox CLI
# https://github.com/realm/SwiftLint

# Paths to include in linting
included:
  - Sources
  - Tests

# Paths to exclude from linting
excluded:
  - .build
  - .swiftpm
  - Package.swift

# Rules to enable/disable
disabled_rules:
  - line_length # Disabled because CLI help text can be long

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - no_space_in_method_call
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - url
    - uri

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Custom rules
custom_rules:
  no_print:
    name: "Avoid print statements"
    regex: "\\bprint\\("
    message: "Use proper logging instead of print statements"
    severity: warning
  
  no_force_cast:
    name: "Avoid force casting"
    regex: "as!"
    message: "Use safe casting (as?) instead of force casting"
    severity: error
    
  no_force_unwrap:
    name: "Avoid force unwrapping"
    regex: "!\\s*$"
    message: "Use safe unwrapping instead of force unwrapping"
    severity: warning

# Reporter type
reporter: "github-actions-logging"