name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]  # Target macOS 14+ only
        swift-version: ['5.9']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
    
    - name: Verify Swift installation
      run: |
        echo "=== Swift Environment Check ==="
        swift --version
        swiftc --version
        which swift
        which swiftc
        echo "Platform: $(uname -a)"
        echo "Xcode version: $(xcode-select --print-path)"
        xcodebuild -version || echo "xcodebuild not available"
        echo "Swift setup completed successfully"
    
    - name: Debug Package Dependencies
      run: |
        echo "=== Package Dependencies Debug ==="
        echo "Checking Package.swift dependencies..."
        swift package describe || echo "Package describe failed"
        echo ""
        echo "Checking for Package.resolved:"
        if [ -f Package.resolved ]; then
          echo "Package.resolved exists:"
          cat Package.resolved
        else
          echo "Package.resolved does not exist"
        fi
        echo ""
        echo "Resolving dependencies..."
        swift package resolve || echo "Package resolve failed"
    
    - name: Cache Swift dependencies
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-swift-${{ hashFiles('Package.swift', 'Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    
    - name: Build project
      run: |
        echo "=== Starting Build Process ==="
        echo "Working directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo ""
        echo "Package.swift contents:"
        cat Package.swift
        echo ""
        echo "Starting swift build with verbose output..."
        # First ensure the project builds successfully
        if swift build --verbose 2>&1 | tee build.log; then
          echo ""
          echo "=== Build completed successfully ==="
        else
          echo ""
          echo "=== BUILD FAILED ==="
          echo "Exit code: $?"
          echo "Last 50 lines of build log:"
          tail -50 build.log || echo "Could not read build log"
          echo ""
          echo "Checking for common build issues..."
          
          # Check for specific error patterns
          if grep -i "error.*not found" build.log; then
            echo "❌ Missing dependency detected"
          fi
          if grep -i "permission denied" build.log; then
            echo "❌ Permission issue detected"
          fi
          if grep -i "unavailable" build.log; then
            echo "❌ API unavailability detected"
          fi
          if grep -i "deprecated" build.log; then
            echo "⚠️  Deprecated API usage detected"
          fi
          
          exit 1
        fi
    
    - name: Run CI-safe tests
      run: |
        echo "=== Starting CI-safe Tests ==="
        echo "Available test targets:"
        swift test --list-tests || echo "Could not list tests"
        echo ""
        echo "Running CITests with verbose output..."
        # Run only CI-safe tests that don't require file system operations
        if swift test --filter CITests --verbose 2>&1 | tee test.log; then
          echo ""
          echo "=== CI tests completed successfully ==="
        else
          echo ""
          echo "=== TESTS FAILED ==="
          echo "Exit code: $?"
          echo "Last 50 lines of test log:"
          tail -50 test.log || echo "Could not read test log"
          echo ""
          echo "Checking for common test issues..."
          
          # Check for specific test error patterns
          if grep -i "test.*failed" test.log; then
            echo "❌ Test failures detected"
          fi
          if grep -i "compilation failed" test.log; then
            echo "❌ Test compilation failed"
          fi
          if grep -i "no tests ran" test.log; then
            echo "❌ No tests executed"
          fi
          
          exit 1
        fi
    
    - name: Environment Debug (on failure)
      if: failure()
      run: |
        echo "=== FAILURE ENVIRONMENT DEBUG ==="
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo ""
        echo "Build directory contents:"
        ls -la .build/ || echo "No .build directory"
        echo ""
        echo "Environment variables:"
        env | grep -E "(SWIFT|XCODE|PATH)" || echo "No relevant env vars found"
        echo ""
        echo "Process list (Swift related):"
        ps aux | grep -i swift || echo "No Swift processes"
        echo ""
        echo "Available disk space:"
        df -h
        echo ""
        echo "Memory usage:"
        vm_stat || echo "vm_stat not available"
    
    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ci-logs-${{ matrix.os }}
        path: |
          build.log
          test.log
        retention-days: 7

  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging || echo "SwiftLint completed with warnings"


  build-validation:
    name: Build Validation
    runs-on: macos-latest
    needs: [test, lint]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.9'
    
    - name: Verify Build Environment
      run: |
        echo "=== Build Validation Environment Check ==="
        swift --version
        swiftc --version
        which swift
        which swiftc
        echo "Platform: $(uname -a)"
        echo "Xcode version: $(xcode-select --print-path)"
        xcodebuild -version || echo "xcodebuild not available"
        echo "Working directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Build validation environment verified"
    
    - name: Debug Release Dependencies
      run: |
        echo "=== Release Build Dependencies Debug ==="
        echo "Checking Package.swift for release build..."
        cat Package.swift
        echo ""
        echo "Resolving dependencies for release build..."
        swift package resolve || echo "Package resolve failed"
        echo ""
        echo "Package describe for release build:"
        swift package describe || echo "Package describe failed"
    
    - name: Build release configuration
      run: |
        echo "=== Starting Release Build Process ==="
        echo "Building with release configuration and verbose output..."
        if swift build -c release --verbose 2>&1 | tee release-build.log; then
          echo ""
          echo "=== Release build completed successfully ==="
          
          echo ""
          echo "=== Debugging Build Output Structure ==="
          echo "Current working directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo ""
          echo "Contents of .build directory:"
          ls -la .build/ || echo "No .build directory found"
          echo ""
          echo "All subdirectories in .build:"
          find .build -type d -maxdepth 3 2>/dev/null | sort || echo "Could not list .build subdirectories"
          echo ""
          echo "All executables in .build:"
          find .build -type f -name "vox" 2>/dev/null || echo "No vox executables found"
          echo ""
          echo "All files in .build (first 20):"
          find .build -type f | head -20 || echo "Could not list .build files"
          
        else
          echo ""
          echo "=== RELEASE BUILD FAILED ==="
          echo "Exit code: $?"
          echo "Last 50 lines of release build log:"
          tail -50 release-build.log || echo "Could not read release build log"
          echo ""
          echo "Checking for common release build issues..."
          
          # Check for specific error patterns
          if grep -i "error.*not found" release-build.log; then
            echo "❌ Missing dependency detected in release build"
          fi
          if grep -i "permission denied" release-build.log; then
            echo "❌ Permission issue detected in release build"
          fi
          if grep -i "unavailable" release-build.log; then
            echo "❌ API unavailability detected in release build"
          fi
          if grep -i "optimization" release-build.log; then
            echo "⚠️  Optimization issue detected in release build"
          fi
          if grep -i "linking" release-build.log; then
            echo "❌ Linking issue detected in release build"
          fi
          if grep -i "architecture" release-build.log; then
            echo "❌ Architecture issue detected in release build"
          fi
          
          exit 1
        fi
    
    - name: Create universal binary (if on macOS)
      run: |
        echo "=== Starting Universal Binary Creation ==="
        
        # Check current architecture
        echo "Current architecture: $(uname -m)"
        echo "Current build artifacts:"
        ls -la .build/ || echo "No .build directory found"
        
        echo ""
        echo "=== Searching for Binary ==="
        # Search for the vox binary in various possible locations
        echo "Searching for vox executable..."
        VOX_BINARY=""
        
        # Check common locations
        for location in \
          ".build/release/vox" \
          ".build/debug/vox" \
          ".build/arm64-apple-macosx/release/vox" \
          ".build/x86_64-apple-macosx/release/vox" \
          ".build/arm64-apple-macosx/debug/vox" \
          ".build/x86_64-apple-macosx/debug/vox"; do
          
          if [ -f "$location" ]; then
            echo "✅ Found binary at: $location"
            VOX_BINARY="$location"
            break
          else
            echo "❌ Not found at: $location"
          fi
        done
        
        # If not found in standard locations, search more broadly
        if [ -z "$VOX_BINARY" ]; then
          echo ""
          echo "Searching for any vox executable in .build..."
          FOUND_BINARIES=$(find .build -name "vox" -type f -executable 2>/dev/null || true)
          
          if [ -n "$FOUND_BINARIES" ]; then
            echo "Found vox executables:"
            echo "$FOUND_BINARIES"
            # Use the first one found
            VOX_BINARY=$(echo "$FOUND_BINARIES" | head -1)
            echo "Using: $VOX_BINARY"
          else
            echo "No vox executables found in .build directory"
          fi
        fi
        
        # Verify we found a binary
        if [ -z "$VOX_BINARY" ] || [ ! -f "$VOX_BINARY" ]; then
          echo ""
          echo "❌ Binary not found at any expected location"
          echo "Available files in .build/:"
          find .build -name "*vox*" -type f 2>/dev/null || echo "No vox-related files found"
          echo ""
          echo "All executable files in .build/:"
          find .build -type f -executable 2>/dev/null || echo "No executable files found"
          exit 1
        fi
        
        echo ""
        echo "=== Processing Found Binary ==="
        echo "Using binary: $VOX_BINARY"
        echo "Binary info:"
        file "$VOX_BINARY"
        lipo -info "$VOX_BINARY" 2>/dev/null || echo "Binary architecture info not available"
        ls -la "$VOX_BINARY"
        
        echo ""
        echo "Copying binary to workspace..."
        cp "$VOX_BINARY" vox-universal
        chmod +x vox-universal
        
        echo "✅ Binary copied successfully"
        
        echo ""
        echo "Verifying final binary..."
        file vox-universal
        lipo -info vox-universal 2>/dev/null || echo "Binary architecture info not available"
        ls -la vox-universal
    
    - name: Test CLI functionality
      run: |
        echo "=== Testing CLI Functionality ==="
        
        echo "Making binary executable..."
        chmod +x vox-universal
        
        echo "Checking binary permissions and properties..."
        ls -la vox-universal
        file vox-universal
        
        echo ""
        echo "Testing help command..."
        if ./vox-universal --help 2>&1 | tee cli-help.log; then
          echo "✅ Help command executed successfully"
        else
          echo "⚠️ Help command returned non-zero exit code (this may be normal)"
          echo "Help output:"
          cat cli-help.log || echo "Could not read help output"
        fi
        
        echo ""
        echo "Testing version command..."
        if ./vox-universal --version 2>&1 | tee cli-version.log; then
          echo "✅ Version command executed successfully"
        else
          echo "⚠️ Version command returned non-zero exit code (this may be normal)"
          echo "Version output:"
          cat cli-version.log || echo "Could not read version output"
        fi
        
        echo ""
        echo "CLI functionality testing completed"
    
    - name: Build Validation Debug (on failure)
      if: failure()
      run: |
        echo "=== BUILD VALIDATION FAILURE DEBUG ==="
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo ""
        echo "Build directory contents:"
        ls -la .build/ || echo "No .build directory"
        echo ""
        echo "Release build directory:"
        ls -la .build/x86_64-apple-macosx/release/ || echo "No release directory"
        echo ""
        echo "Environment variables:"
        env | grep -E "(SWIFT|XCODE|PATH)" || echo "No relevant env vars found"
        echo ""
        echo "Available disk space:"
        df -h
        echo ""
        echo "Memory usage:"
        vm_stat || echo "vm_stat not available"
    
    - name: Upload build validation logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-validation-logs
        path: |
          release-build.log
          cli-help.log
          cli-version.log
        retention-days: 7
    
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: vox-universal-binary
        path: vox-universal
        retention-days: 7
